  default: &default
    adapter: mysql2
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: <%=ENV['DB_HOST']%>
    database: <%=ENV['DB_NAME']%>
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>

  development:
    adapter: mysql2
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: <%=ENV['DB_HOST']%>
    database: <%=ENV['DB_NAME']%>
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>

  test:
    <<: *default
    database: <%=ENV['DB_NAME_TEST']%>

  production:
    <<: *default
    database: <%=ENV['DB_NAME']%>
